name: Integration Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Project 
        run: mvn clean install -DskipTests
        
      - name: Trigger API AutomationTest Workflow
        run: |
                # Trigger the workflow in api-automationtest repository
                curl -X POST -H "Authorization: Bearer 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>" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://github.com/diptideepali/demo-service/actions/workflows/65943127/dispatches \
                     -d '{"ref":"main",
                          "inputs": {
                                      "test-class-name": "com.manish.api.automation.MathSuiteExecutionTest"
                                    }
                          }'
