name: Integration Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Project 
        run: mvn clean install -DskipTests
        
      - name: Set Project Name
        id: set-project-name
        run: |
          # Extract the project name dynamically (e.g., from a file)
          project_name="NAXGroup"
          echo "::set-output name=project_name::$project_name"
      
      - name: Upload Project Name as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-name
          path: project-name.txt
